services:
  nextapp:
    build: .
    container_name: nextapp
    labels:
      - traefik.enable=true
      - traefik.http.routers.nextapp-http.rule=Host(`dev.automationsflow.com`)
      - traefik.http.routers.nextapp-http.entrypoints=web
      - traefik.http.routers.nextapp-http.middlewares=redirect-to-https
      - traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https
      - traefik.http.routers.nextapp.rule=Host(`dev.automationsflow.com`)
      - traefik.http.routers.nextapp.entrypoints=websecure
      - traefik.http.routers.nextapp.tls=true
      - traefik.http.routers.nextapp.tls.certresolver=mytlschallenge
      - traefik.http.services.nextapp.loadbalancer.server.port=3000
    restart: always
    ports:
      - 3000
    networks:
      - root_default

networks:
  root_default:
    external: true
